/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_duncte123_lottieconverter_LottieConverter */

#ifndef _Included_me_duncte123_lottieconverter_LottieConverter
#define _Included_me_duncte123_lottieconverter_LottieConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_duncte123_lottieconverter_LottieConverter
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_duncte123_lottieconverter_LottieConverter_getMessage
  (JNIEnv *, jobject);

/*
 * Class:     me_duncte123_lottieconverter_LottieConverter
 * Method:    generateGif
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_me_duncte123_lottieconverter_LottieConverter_generateGif
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
